check,constraint,passed,constraint_message
Data quality checks for movie data,"UniquenessConstraint(Uniqueness(Stream(user_id, ?),None))",Failure,"Can't execute the assertion: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
  File ""/opt/miniconda3/envs/spark_deequ_env/lib/python3.9/site-packages/py4j/clientserver.py"", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
  File ""/opt/miniconda3/envs/spark_deequ_env/lib/python3.9/site-packages/pydeequ/scala_utils.py"", line 37, in apply
    return self.lambda_function(arg)
TypeError: 'float' object is not callable
!"
Data quality checks for movie data,"MinimumConstraint(Minimum(rating,None))",Success,
Data quality checks for movie data,"MaximumConstraint(Maximum(rating,None))",Success,
Data quality checks for movie data,"MinimumConstraint(Minimum(Action,None))",Success,
Data quality checks for movie data,"MaximumConstraint(Maximum(Action,None))",Success,
Data quality checks for movie data,"MinimumConstraint(Minimum(Comedy,None))",Success,
Data quality checks for movie data,"MaximumConstraint(Maximum(Comedy,None))",Success,
Data quality checks for movie data,"MinimumConstraint(Minimum(Crime,None))",Success,
Data quality checks for movie data,"MaximumConstraint(Maximum(Crime,None))",Success,
Data quality checks for movie data,"CompletenessConstraint(Completeness(user_id,None))",Success,
Data quality checks for movie data,"CompletenessConstraint(Completeness(movie_id,None))",Success,
Data quality checks for movie data,"CompletenessConstraint(Completeness(rating,None))",Success,
Data quality checks for movie data,"CompletenessConstraint(Completeness(title,None))",Success,
Data quality checks for movie data,"CompletenessConstraint(Completeness(Action,None))",Success,
Data quality checks for movie data,"CompletenessConstraint(Completeness(Comedy,None))",Success,
Data quality checks for movie data,"CompletenessConstraint(Completeness(Crime,None))",Success,
